{{- $appName := "{{ .Values.springboot.appName }}" }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ $appName }}
  ports:
  - port: 8080
    name: http
