---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: openshift-gitops
  annotations:
#   argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo
  source:
    repoURL: 'https://github.com/duttap06/openshift-cluster-config.git'
    path: apps/helm-kustomize
    kustomize: {}
    targetRevision: master
  destination:
    namespace: demo
    server: local-cluster
  project: default      
  syncPolicy:
#   automated: {}
